/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.jepos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author john
 */

enum MODE { CREATE, EDIT };

public class account extends javax.swing.JFrame {

    MODE mode;
    Staff staff;
    /**
     * Creates new form account
     */
    public account(MODE mode, Staff staff) throws SQLException {
        initComponents();
        this.mode = mode;
        this.staff = staff;
        setUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetails = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnGenerateUsername = new javax.swing.JButton();
        btnGeneratePassword = new javax.swing.JButton();
        cbbRole = new javax.swing.JComboBox<>();
        pnlControl = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("Staff ID:");

        lblUsername.setText("Username: ");

        lblPassword.setText("Password:");

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        lblRole.setText("Role:");

        btnGenerateUsername.setText("Generate");
        btnGenerateUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateUsernameActionPerformed(evt);
            }
        });

        btnGeneratePassword.setText("Generate");
        btnGeneratePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePasswordActionPerformed(evt);
            }
        });

        cbbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addGap(18, 18, 18)
                        .addComponent(txtLastName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addGap(18, 18, 18)
                        .addComponent(txtFirstName))
                    .addGroup(pnlDetailsLayout.createSequentialGroup()
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblUsername))
                        .addGap(19, 19, 19)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGenerateUsername)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDetailsLayout.createSequentialGroup()
                            .addComponent(lblRole)
                            .addGap(54, 54, 54)
                            .addComponent(cbbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlDetailsLayout.createSequentialGroup()
                            .addComponent(lblPassword)
                            .addGap(27, 27, 27)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGeneratePassword)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateUsername))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratePassword))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cbbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        btnSave.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setUp() throws SQLException
    {
        cbbRole.removeAllItems();
        for(ROLE role : ROLE.values())
        { // Add all roles to cbbRole
            cbbRole.addItem( role.toString() );
        }
        
        if(mode == MODE.EDIT)
        { // We're in edit mode (edit existing staff)
            btnSave.setText("SAVE");
            txtUsername.setEnabled(false); // Don't let user change an existing username
            btnGenerateUsername.setEnabled(false); // ... or generate one.
        }
        else if(mode == MODE.CREATE)
        { // We're in create mode (create new staff)
            btnSave.setText("CREATE");
            staff.setFirstName("John");
            staff.setLastName("Doe");
        }
        
        txtId.setText( Integer.toString(staff.getId()) );
        txtFirstName.setText (staff.getFirstName() );
        txtLastName.setText( staff.getLastName() );
        if( mode == MODE.EDIT )
        { // We're editing an existing user
            txtUsername.setText( staff.getUsername() );
            txtPassword.setText( staff.getPassword() );
        }
        else
        { // We're creating a new user, set default username/password
            txtUsername.setText( "blank" );
            txtPassword.setText( "changeme" );
        }
        cbbRole.setSelectedItem( staff.getRole().toString() );
        
        txtId.setEnabled(false); // Disable this as it should not be edited manually.
        
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if( txtUsername.getText().equals("blank") )
        { // Username was left as default "blank", abort
            JOptionPane.showMessageDialog( this,
                        "The username was left as \"blank\", set one first!",
                        "Error: blank username!",
                        JOptionPane.ERROR_MESSAGE
                        );
        }
        else if( txtPassword.getText().equals("changeme") )
        { // Password was left as default "changeme", abort
            JOptionPane.showMessageDialog( this,
                        "The password is \"changeme\" for a reason!",
                        "Error: change password!",
                        JOptionPane.ERROR_MESSAGE
            );
        }
        else
        { // All good, continue!
            staff.setFirstName( txtFirstName.getText() );
            staff.setLastName( txtLastName.getText() );
            staff.setUsername( txtUsername.getText() );
            staff.setPassword( txtPassword.getText() );
            staff.setRole( ROLE.valueOf(cbbRole.getSelectedItem().toString()) );

            // DEBUG CODE
            System.out.println("\nStaff member to be written to the database:"
            +"\nID: "+staff.getId()
            +"\nNAME: "+staff.getFirstName()+" "+staff.getLastName()
            +"\nUSERNAME: "+staff.getUsername()
            +"\nPASSWORD: "+staff.getPassword()
            +"\nROLE: "+staff.getRole().toString()+"\n"
            ); // END OF DEBUG SECTION
            
            try
            {
                staff.save();
                JOptionPane.showMessageDialog( this,
                        "The user \""+staff.getUsername()+"\" has been written to the database!",
                        "User written to database!",
                        JOptionPane.INFORMATION_MESSAGE
                );
                this.setVisible(false);
            }
            catch (SQLException ex) { Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex); }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGeneratePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePasswordActionPerformed
        // TODO add your handling code here:
        System.out.println("Staff.generatePassword() not yet implemented!");
    }//GEN-LAST:event_btnGeneratePasswordActionPerformed

    private void btnGenerateUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateUsernameActionPerformed
        staff.setFirstName( txtFirstName.getText() );
        staff.setLastName( txtLastName.getText() );
        try { staff.setUsername( staff.generateUsername() ); }
        catch (SQLException ex) { }
        txtUsername.setText( staff.getUsername() );
    }//GEN-LAST:event_btnGenerateUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneratePassword;
    private javax.swing.JButton btnGenerateUsername;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbbRole;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
