/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.jepos;

import java.util.logging.Level;
import java.util.logging.Logger;
// UI
import javax.swing.JOptionPane;
// Database
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author john
 */

enum ROLE{ SALES, MANAGER, TECH } // 0:Sales, 1:Manager, 2:Tech

public class login extends javax.swing.JDialog 
{
    // Logged in username
    static String username;
    // Logged in role
    static ROLE role;
    // Hold list of products from database TODO: REMOVE
    ArrayList products = new ArrayList<Product>();
    // Object to hold inventory
    static Inventory inventory;
    // The logged-in user
    static Staff user;

    /**
     * Creates new form login
     */
    public login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try { // DELET THIS
            inventory = new Inventory();
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtUsername.setText("Username");

        btnLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPassword.setText("jPasswordField1");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Placeholder accounts:
        //   Sales - stephen, dogsauce99
        //   Manager - max, beanjuice51
        //   Tech - tim, danksouls83
        
        username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        // Check user exists, password matches
        try
        {
            if(Staff.userExists(username))
            { // User exists
                if(Staff.authenticate(username, password))
                { // Password matched
                    logIn(username);
                    JOptionPane.showMessageDialog(
                        this,
                        "Successfully logged in as " + user.getUsername() + " ("+user.getRole()+")" + "!",
                        "Success!",
                        JOptionPane.INFORMATION_MESSAGE);
                    showMainUI();
                    this.dispose();
                }
                else
                { // Password does not match
                    JOptionPane.showMessageDialog(
                        this,
                        "Password incorrect!",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(username.equals("refilldb"))
            { // Entering "refilldb" as username will fill the database with some test values
                Database.fillTestDatabase();
                JOptionPane.showMessageDialog(
                        this,
                        "Filled the database with some test values! Now restart the system and look at the console.",
                        "Test values created!",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else
            { // Username does not match any user in users
                JOptionPane.showMessageDialog(
                        this,
                        "User " + username + " does not exist!",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }               
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // DEBUG INFO
            ArrayList<Staff> staffList = Staff.getAllStaff();
            System.out.println("---TEST-ACCOUNTS----------------------------------");
            for(Staff s : staffList)
            {
                System.out.println(
                        "User: " + s.getUsername() + "\t"
                        + "Pass: " + s.getPassword() + "\t"
                        + "Role: " + s.getRole()
                );
            }
            System.out.println("--------------------------------------------------");
            Database.close();
            // END DEBUG INFO
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void showMainUI()
    { // Display the main user interface
        ui ui = new ui();
        ui.setVisible(true);
    }
    
    private void logIn(String username) throws SQLException
    { // Store the logged in user after successful authentication
        user = Staff.getByUsername(username);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login dialog = new login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
